--- !ditz.rubyforge.org,2008-03-06/project 
name: god_web
version: "0.2"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: god_web
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.2.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-05-19 13:57:45.625914 Z
    - Jesse Newland <jnewland@gmail.com>
    - created
    - ""
